DELETE FROM products;
INSERT INTO products (id, name, description, price, stock) VALUES (1, 'Pantal≤n - Talla XXL - Verde - (Deportivo)', 'Ideal para uso diario.', 1058.0, 177);
INSERT INTO products (id, name, description, price, stock) VALUES (2, 'Camiseta - Talla XXL - Blanco - (Deportivo)', 'Prenda c≤moda y ligera.', 510.0, 33);
INSERT INTO products (id, name, description, price, stock) VALUES (3, 'Camiseta - Talla S - Negro - (Casual)', 'Dise±o moderno y elegante.', 1292.0, 457);
INSERT INTO products (id, name, description, price, stock) VALUES (4, 'Falda - Talla S - Blanco - (Casual)', 'Ideal para uso diario.', 1138.0, 414);
INSERT INTO products (id, name, description, price, stock) VALUES (5, 'Sudadera - Talla XL - Verde - (Formal)', 'Dise±o moderno y elegante.', 603.0, 151);
INSERT INTO products (id, name, description, price, stock) VALUES (6, 'Chaqueta - Talla S - Amarillo - (Deportivo)', 'Prenda c≤moda y ligera.', 961.0, 223);
INSERT INTO products (id, name, description, price, stock) VALUES (7, 'Pantal≤n - Talla L - Gris - (Deportivo)', 'Dise±o moderno y elegante.', 1331.0, 436);
INSERT INTO products (id, name, description, price, stock) VALUES (8, 'Falda - Talla XXL - Blanco - (Casual)', 'Prenda c≤moda y ligera.', 1286.0, 441);
INSERT INTO products (id, name, description, price, stock) VALUES (9, 'Sudadera - Talla L - Azul - (Casual)', 'Material de alta calidad.', 889.0, 187);
INSERT INTO products (id, name, description, price, stock) VALUES (10, 'Pantal≤n - Talla XXL - Gris - (Formal)', 'Dise±o moderno y elegante.', 647.0, 462);
INSERT INTO products (id, name, description, price, stock) VALUES (11, 'Chaqueta - Talla S - Azul - (Deportivo)', 'Material de alta calidad.', 464.0, 65);
INSERT INTO products (id, name, description, price, stock) VALUES (12, 'Pantal≤n - Talla M - Blanco - (Formal)', 'Material de alta calidad.', 786.0, 65);
INSERT INTO products (id, name, description, price, stock) VALUES (13, 'Falda - Talla XL - Azul - (Deportivo)', 'Material de alta calidad.', 762.0, 454);
INSERT INTO products (id, name, description, price, stock) VALUES (14, 'Chaqueta - Talla L - Gris - (Casual)', 'Dise±o moderno y elegante.', 430.0, 193);
INSERT INTO products (id, name, description, price, stock) VALUES (15, 'Falda - Talla L - Azul - (Deportivo)', 'Prenda c≤moda y ligera.', 952.0, 246);
INSERT INTO products (id, name, description, price, stock) VALUES (16, 'Falda - Talla XL - Blanco - (Formal)', 'Prenda c≤moda y ligera.', 883.0, 0);
INSERT INTO products (id, name, description, price, stock) VALUES (17, 'Camiseta - Talla S - Azul - (Deportivo)', 'Material de alta calidad.', 1128.0, 348);
INSERT INTO products (id, name, description, price, stock) VALUES (18, 'Falda - Talla L - Gris - (Deportivo)', 'Prenda c≤moda y ligera.', 1224.0, 0);
INSERT INTO products (id, name, description, price, stock) VALUES (19, 'Chaqueta - Talla L - Azul - (Formal)', 'Prenda c≤moda y ligera.', 416.0, 0);
INSERT INTO products (id, name, description, price, stock) VALUES (20, 'Camiseta - Talla XXL - Rojo - (Deportivo)', 'Dise±o moderno y elegante.', 1292.0, 302);
INSERT INTO products (id, name, description, price, stock) VALUES (21, 'Pantal≤n - Talla L - Verde - (Formal)', 'Material de alta calidad.', 1017.0, 334);
INSERT INTO products (id, name, description, price, stock) VALUES (22, 'Sudadera - Talla XL - Azul - (Deportivo)', 'Dise±o moderno y elegante.', 1288.0, 0);
INSERT INTO products (id, name, description, price, stock) VALUES (23, 'Pantal≤n - Talla S - Verde - (Casual)', 'Prenda c≤moda y ligera.', 525.0, 257);
INSERT INTO products (id, name, description, price, stock) VALUES (24, 'Camiseta - Talla M - Negro - (Formal)', 'Dise±o moderno y elegante.', 1386.0, 0);
INSERT INTO products (id, name, description, price, stock) VALUES (25, 'Sudadera - Talla S - Negro - (Deportivo)', 'Perfecta para actividades al aire libre.', 596.0, 166);
INSERT INTO products (id, name, description, price, stock) VALUES (26, 'Camiseta - Talla S - Verde - (Casual)', 'Material de alta calidad.', 503.0, 0);
INSERT INTO products (id, name, description, price, stock) VALUES (27, 'Sudadera - Talla S - Verde - (Casual)', 'Ideal para uso diario.', 967.0, 64);
INSERT INTO products (id, name, description, price, stock) VALUES (28, 'Falda - Talla XL - Negro - (Deportivo)', 'Perfecta para actividades al aire libre.', 464.0, 196);
INSERT INTO products (id, name, description, price, stock) VALUES (29, 'Chaqueta - Talla XL - Amarillo - (Casual)', 'Dise±o moderno y elegante.', 1465.0, 282);
INSERT INTO products (id, name, description, price, stock) VALUES (30, 'Camisa - Talla M - Verde - (Casual)', 'Ideal para uso diario.', 1100.0, 206);
INSERT INTO products (id, name, description, price, stock) VALUES (31, 'Falda - Talla XXL - Blanco - (Casual)', 'Prenda c≤moda y ligera.', 1006.0, 0);
INSERT INTO products (id, name, description, price, stock) VALUES (32, 'Camiseta - Talla S - Rojo - (Deportivo)', 'Perfecta para actividades al aire libre.', 1010.0, 298);
INSERT INTO products (id, name, description, price, stock) VALUES (33, 'Falda - Talla M - Azul - (Deportivo)', 'Dise±o moderno y elegante.', 1120.0, 482);
INSERT INTO products (id, name, description, price, stock) VALUES (34, 'Camisa - Talla L - Blanco - (Formal)', 'Ideal para uso diario.', 548.0, 0);
INSERT INTO products (id, name, description, price, stock) VALUES (35, 'Camisa - Talla XXL - Verde - (Deportivo)', 'Dise±o moderno y elegante.', 783.0, 264);
INSERT INTO products (id, name, description, price, stock) VALUES (36, 'Sudadera - Talla XXL - Amarillo - (Deportivo)', 'Material de alta calidad.', 1261.0, 194);
INSERT INTO products (id, name, description, price, stock) VALUES (37, 'Sudadera - Talla S - Negro - (Formal)', 'Ideal para uso diario.', 925.0, 208);
INSERT INTO products (id, name, description, price, stock) VALUES (38, 'Pantal≤n - Talla XXL - Rojo - (Formal)', 'Material de alta calidad.', 1379.0, 19);
INSERT INTO products (id, name, description, price, stock) VALUES (39, 'Pantal≤n - Talla M - Verde - (Casual)', 'Dise±o moderno y elegante.', 1338.0, 340);
INSERT INTO products (id, name, description, price, stock) VALUES (40, 'Pantal≤n - Talla M - Negro - (Casual)', 'Prenda c≤moda y ligera.', 1295.0, 0);
INSERT INTO products (id, name, description, price, stock) VALUES (41, 'Chaqueta - Talla M - Rojo - (Deportivo)', 'Material de alta calidad.', 777.0, 142);
INSERT INTO products (id, name, description, price, stock) VALUES (42, 'Chaqueta - Talla S - Amarillo - (Casual)', 'Dise±o moderno y elegante.', 1089.0, 333);
INSERT INTO products (id, name, description, price, stock) VALUES (43, 'Sudadera - Talla XXL - Rojo - (Formal)', 'Perfecta para actividades al aire libre.', 1271.0, 304);
INSERT INTO products (id, name, description, price, stock) VALUES (44, 'Camiseta - Talla S - Azul - (Deportivo)', 'Dise±o moderno y elegante.', 424.0, 443);
INSERT INTO products (id, name, description, price, stock) VALUES (45, 'Sudadera - Talla XL - Rojo - (Deportivo)', 'Material de alta calidad.', 840.0, 376);
INSERT INTO products (id, name, description, price, stock) VALUES (46, 'Camisa - Talla S - Rojo - (Formal)', 'Perfecta para actividades al aire libre.', 1090.0, 121);
INSERT INTO products (id, name, description, price, stock) VALUES (47, 'Chaqueta - Talla XL - Blanco - (Formal)', 'Ideal para uso diario.', 608.0, 0);
INSERT INTO products (id, name, description, price, stock) VALUES (48, 'Camiseta - Talla XXL - Amarillo - (Formal)', 'Ideal para uso diario.', 548.0, 480);
INSERT INTO products (id, name, description, price, stock) VALUES (49, 'Sudadera - Talla XL - Blanco - (Deportivo)', 'Ideal para uso diario.', 1167.0, 0);
INSERT INTO products (id, name, description, price, stock) VALUES (50, 'Sudadera - Talla XL - Blanco - (Deportivo)', 'Ideal para uso diario.', 717.0, 248);
INSERT INTO products (id, name, description, price, stock) VALUES (51, 'Falda - Talla M - Blanco - (Casual)', 'Dise±o moderno y elegante.', 1071.0, 323);
INSERT INTO products (id, name, description, price, stock) VALUES (52, 'Camisa - Talla XXL - Gris - (Casual)', 'Material de alta calidad.', 963.0, 0);
INSERT INTO products (id, name, description, price, stock) VALUES (53, 'Pantal≤n - Talla XL - Azul - (Deportivo)', 'Dise±o moderno y elegante.', 815.0, 405);
INSERT INTO products (id, name, description, price, stock) VALUES (54, 'Falda - Talla L - Azul - (Deportivo)', 'Prenda c≤moda y ligera.', 805.0, 0);
INSERT INTO products (id, name, description, price, stock) VALUES (55, 'Camisa - Talla L - Blanco - (Casual)', 'Dise±o moderno y elegante.', 551.0, 111);
INSERT INTO products (id, name, description, price, stock) VALUES (56, 'Chaqueta - Talla XL - Negro - (Formal)', 'Perfecta para actividades al aire libre.', 876.0, 0);
INSERT INTO products (id, name, description, price, stock) VALUES (57, 'Camiseta - Talla S - Rojo - (Casual)', 'Dise±o moderno y elegante.', 1049.0, 37);
INSERT INTO products (id, name, description, price, stock) VALUES (58, 'Camisa - Talla M - Rojo - (Casual)', 'Dise±o moderno y elegante.', 655.0, 0);
INSERT INTO products (id, name, description, price, stock) VALUES (59, 'Chaqueta - Talla XL - Gris - (Deportivo)', 'Ideal para uso diario.', 1052.0, 260);
INSERT INTO products (id, name, description, price, stock) VALUES (60, 'Pantal≤n - Talla M - Verde - (Deportivo)', 'Perfecta para actividades al aire libre.', 960.0, 405);
INSERT INTO products (id, name, description, price, stock) VALUES (61, 'Chaqueta - Talla XXL - Negro - (Formal)', 'Material de alta calidad.', 1055.0, 297);
INSERT INTO products (id, name, description, price, stock) VALUES (62, 'Chaqueta - Talla S - Verde - (Formal)', 'Perfecta para actividades al aire libre.', 1180.0, 473);
INSERT INTO products (id, name, description, price, stock) VALUES (63, 'Pantal≤n - Talla L - Rojo - (Casual)', 'Prenda c≤moda y ligera.', 708.0, 0);
INSERT INTO products (id, name, description, price, stock) VALUES (64, 'Falda - Talla M - Gris - (Deportivo)', 'Material de alta calidad.', 874.0, 374);
INSERT INTO products (id, name, description, price, stock) VALUES (65, 'Falda - Talla L - Verde - (Casual)', 'Ideal para uso diario.', 685.0, 0);
INSERT INTO products (id, name, description, price, stock) VALUES (66, 'Camisa - Talla XL - Azul - (Deportivo)', 'Perfecta para actividades al aire libre.', 1151.0, 441);
INSERT INTO products (id, name, description, price, stock) VALUES (67, 'Pantal≤n - Talla XL - Azul - (Deportivo)', 'Material de alta calidad.', 1331.0, 0);
INSERT INTO products (id, name, description, price, stock) VALUES (68, 'Sudadera - Talla S - Blanco - (Deportivo)', 'Dise±o moderno y elegante.', 571.0, 0);
INSERT INTO products (id, name, description, price, stock) VALUES (69, 'Camisa - Talla L - Negro - (Deportivo)', 'Ideal para uso diario.', 835.0, 486);
INSERT INTO products (id, name, description, price, stock) VALUES (70, 'Camiseta - Talla XL - Rojo - (Casual)', 'Perfecta para actividades al aire libre.', 1225.0, 0);
INSERT INTO products (id, name, description, price, stock) VALUES (71, 'Chaqueta - Talla L - Blanco - (Casual)', 'Ideal para uso diario.', 1070.0, 320);
INSERT INTO products (id, name, description, price, stock) VALUES (72, 'Camiseta - Talla L - Amarillo - (Casual)', 'Dise±o moderno y elegante.', 1356.0, 148);
INSERT INTO products (id, name, description, price, stock) VALUES (73, 'Falda - Talla L - Gris - (Deportivo)', 'Material de alta calidad.', 1283.0, 252);
INSERT INTO products (id, name, description, price, stock) VALUES (74, 'Pantal≤n - Talla XL - Rojo - (Deportivo)', 'Perfecta para actividades al aire libre.', 913.0, 0);
INSERT INTO products (id, name, description, price, stock) VALUES (75, 'Chaqueta - Talla S - Verde - (Formal)', 'Ideal para uso diario.', 507.0, 136);
INSERT INTO products (id, name, description, price, stock) VALUES (76, 'Chaqueta - Talla L - Azul - (Casual)', 'Perfecta para actividades al aire libre.', 407.0, 18);
INSERT INTO products (id, name, description, price, stock) VALUES (77, 'Sudadera - Talla XL - Gris - (Formal)', 'Dise±o moderno y elegante.', 516.0, 0);
INSERT INTO products (id, name, description, price, stock) VALUES (78, 'Camiseta - Talla M - Gris - (Formal)', 'Prenda c≤moda y ligera.', 457.0, 360);
INSERT INTO products (id, name, description, price, stock) VALUES (79, 'Camiseta - Talla L - Blanco - (Deportivo)', 'Ideal para uso diario.', 445.0, 103);
INSERT INTO products (id, name, description, price, stock) VALUES (80, 'Falda - Talla S - Verde - (Deportivo)', 'Prenda c≤moda y ligera.', 680.0, 0);
INSERT INTO products (id, name, description, price, stock) VALUES (81, 'Sudadera - Talla M - Negro - (Casual)', 'Dise±o moderno y elegante.', 1008.0, 319);
INSERT INTO products (id, name, description, price, stock) VALUES (82, 'Pantal≤n - Talla M - Rojo - (Formal)', 'Dise±o moderno y elegante.', 720.0, 0);
INSERT INTO products (id, name, description, price, stock) VALUES (83, 'Sudadera - Talla XXL - Azul - (Casual)', 'Material de alta calidad.', 801.0, 0);
INSERT INTO products (id, name, description, price, stock) VALUES (84, 'Sudadera - Talla XXL - Rojo - (Casual)', 'Perfecta para actividades al aire libre.', 1167.0, 218);
INSERT INTO products (id, name, description, price, stock) VALUES (85, 'Camisa - Talla M - Rojo - (Casual)', 'Material de alta calidad.', 527.0, 19);
INSERT INTO products (id, name, description, price, stock) VALUES (86, 'Pantal≤n - Talla S - Gris - (Casual)', 'Perfecta para actividades al aire libre.', 753.0, 0);
INSERT INTO products (id, name, description, price, stock) VALUES (87, 'Falda - Talla L - Verde - (Casual)', 'Ideal para uso diario.', 1390.0, 317);
INSERT INTO products (id, name, description, price, stock) VALUES (88, 'Camisa - Talla M - Azul - (Casual)', 'Material de alta calidad.', 1438.0, 253);
INSERT INTO products (id, name, description, price, stock) VALUES (89, 'Camiseta - Talla L - Verde - (Formal)', 'Perfecta para actividades al aire libre.', 778.0, 449);
INSERT INTO products (id, name, description, price, stock) VALUES (90, 'Camiseta - Talla M - Verde - (Formal)', 'Perfecta para actividades al aire libre.', 404.0, 350);
INSERT INTO products (id, name, description, price, stock) VALUES (91, 'Chaqueta - Talla XXL - Amarillo - (Deportivo)', 'Dise±o moderno y elegante.', 463.0, 0);
INSERT INTO products (id, name, description, price, stock) VALUES (92, 'Camiseta - Talla S - Gris - (Casual)', 'Ideal para uso diario.', 987.0, 226);
INSERT INTO products (id, name, description, price, stock) VALUES (93, 'Camiseta - Talla L - Blanco - (Deportivo)', 'Material de alta calidad.', 599.0, 100);
INSERT INTO products (id, name, description, price, stock) VALUES (94, 'Pantal≤n - Talla XL - Gris - (Casual)', 'Dise±o moderno y elegante.', 756.0, 249);
INSERT INTO products (id, name, description, price, stock) VALUES (95, 'Camiseta - Talla XL - Negro - (Formal)', 'Perfecta para actividades al aire libre.', 541.0, 245);
INSERT INTO products (id, name, description, price, stock) VALUES (96, 'Falda - Talla L - Negro - (Deportivo)', 'Prenda c≤moda y ligera.', 975.0, 480);
INSERT INTO products (id, name, description, price, stock) VALUES (97, 'Falda - Talla XXL - Azul - (Formal)', 'Perfecta para actividades al aire libre.', 973.0, 51);
INSERT INTO products (id, name, description, price, stock) VALUES (98, 'Sudadera - Talla XXL - Azul - (Casual)', 'Perfecta para actividades al aire libre.', 1491.0, 114);
INSERT INTO products (id, name, description, price, stock) VALUES (99, 'Camiseta - Talla S - Verde - (Formal)', 'Ideal para uso diario.', 1067.0, 391);
INSERT INTO products (id, name, description, price, stock) VALUES (100, 'Chaqueta - Talla XL - Rojo - (Deportivo)', 'Dise±o moderno y elegante.', 1117.0, 347);
